version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres-db-prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-broker-prod
    ports:
      - "5672:5672"   
      - "15672:15672" 
    volumes:
      - rabbitmq_data_prod:/var/lib/rabbitmq

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: backend-api-prod
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}?schema=public
      - RABBITMQ_URL=${RABBITMQ_URL} 
    env_file:
      - ./server/.env
      - ./.env
    command: sh -c "npx prisma db push && node dist/index.js"
    depends_on:
      - db
      - rabbitmq

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: frontend-ui-prod
    ports:
      - "80:80"
    depends_on:
      - backend

  cv-worker:
    build:
      context: ./cv-parser
      dockerfile: Dockerfile
    container_name: python-cv-worker-prod
    environment:
      - RABBITMQ_HOST=rabbitmq 
    depends_on:
      - rabbitmq

volumes:
  pgdata_prod:
  rabbitmq_data_prod:
